---
- name: run show version on remote devices
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: configure the login banner
      junos_banner:
        banner: login
        text: |
          this is my login banner
          that contains a multiline
          string
        state: present
